# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseservicemodel',
            name='rasterbucketservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='api.RasterbucketService'),
        ),
    ]
