# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterbucket',
            name='raster_data',
            field=models.FileField(blank=True, upload_to=b'geebridge'),
        ),
    ]
