# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasterbucket',
            name='owner',
        ),
    ]
