# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 07:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180316_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Process identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='input_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='output_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='rasterbucket',
            name='raster_data',
            field=models.FileField(blank=True, upload_to='geebridge'),
        ),
    ]
