# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_rasterbucket_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterbucket',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rasterbuckets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rasterbucket',
            name='raster_data',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='myfolder'),
        ),
    ]
