# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 14:00
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='input_data',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='output_data',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
