# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_type',
            field=models.CharField(choices=[('TMS', 'tms')], default='tms', max_length=25),
        ),
    ]
