# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapclient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arguments', jsonfield.fields.JSONField(default={})),
            ],
        ),
        migrations.AlterField(
            model_name='process',
            name='algorithm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algorithm', to='mapclient.Algorithm'),
        ),
    ]
